"""
Shared report builder for the analysis studies.

Every study needs to say the same thing twice: aligned columns in the terminal
while it runs, and a readable document afterwards.  Writing both by hand drifts;
tee-ing the terminal output into a fenced code block -- what these studies did
before -- produces a document that is technically complete and practically
unreadable, because a 60-line monospace dump has no headline, no real tables and
nothing to scan for.

So a study declares its content once, through this builder, and gets both:

    rep = Report("analysis/x/x_report.md", "Title", subtitle="one line",
                 source="analysis/x/x_run.py")
    rep.summary(["**32x** on the stage", "but 1.75x on the token"])
    rep.section("A. What happened", "Optional prose.")
    rep.table(["ctx", "cycles"], [["1024", "34,048"]], aligns="lr")
    rep.note("A caveat that must not be missed.")
    rep.save()

Conventions the studies rely on:

  * `summary()` goes at the top under **Key findings** -- the reader who only
    reads three lines should get the result and its main caveat.
  * `note()` renders as a blockquote in markdown and an indented block in the
    terminal.  Use it for the thing that would otherwise be over-read.
  * Cell values are plain strings, formatted by the caller.  No markdown
    emphasis inside cells -- it would leak asterisks into the terminal view.
    Put emphasis in `summary()`, `section()` prose and `note()`.
"""

from typing import List, Optional, Sequence

__all__ = ['Report']


def _md_escape(text: str) -> str:
    """Pipes would break a markdown table cell."""
    return str(text).replace('|', '\\|')


class Report:
    """Builds a markdown document while printing an aligned terminal view."""

    def __init__(self, path: str, title: str, subtitle: str = '',
                 source: str = '', setup: Optional[Sequence[str]] = None,
                 echo: bool = True):
        self.path = path
        self.echo = echo
        self._md: List[str] = [f"# {title}", '']
        if subtitle:
            self._md += [f"*{subtitle}*", '']
        meta = []
        if source:
            meta.append(f"Generated by `{source}` — re-run it to refresh.")
        meta += list(setup or [])
        if meta:
            self._md += ['\n'.join(meta), '']
        if self.echo:
            print(f"{title}")
            if subtitle:
                print(f"  {subtitle}")
            print()

    # ---- Structure ---------------------------------------------------------

    def summary(self, bullets: Sequence[str]) -> 'Report':
        """The three lines a reader who reads nothing else should get."""
        self._md += ['## Key findings', '']
        self._md += [f"- {b}" for b in bullets]
        self._md += ['']
        if self.echo:
            print("Key findings")
            for b in bullets:
                print(f"  - {self._plain(b)}")
            print()
        return self

    def section(self, heading: str, body: str = '') -> 'Report':
        self._md += [f"## {heading}", '']
        if body:
            self._md += [body.strip(), '']
        if self.echo:
            print(f"\n{heading}")
            if body:
                for line in body.strip().splitlines():
                    print(f"  {self._plain(line.strip())}")
            print()
        return self

    def note(self, text: str) -> 'Report':
        """A caveat, rendered as a blockquote."""
        lines = [l.strip() for l in text.strip().splitlines()]
        self._md += ['> ' + '\n> '.join(lines), '']
        if self.echo:
            for line in lines:
                print(f"    {self._plain(line)}")
            print()
        return self

    def table(self, headers: Sequence[str], rows: Sequence[Sequence[str]],
              aligns: str = '', caption: str = '') -> 'Report':
        """One table, rendered as markdown and as aligned terminal columns.

        `aligns` is one character per column: 'l', 'r' or 'c'.  Short or empty
        strings default the remaining columns to right-aligned, which is what
        numbers want and what most of these tables are.
        """
        headers = [str(h) for h in headers]
        rows = [[str(c) for c in r] for r in rows]
        n = len(headers)
        aligns = (aligns + 'r' * n)[:n]

        if caption:
            self._md += [f"**{caption}**", '']
        sep = {'l': ':---', 'r': '---:', 'c': ':---:'}
        self._md += [
            '| ' + ' | '.join(_md_escape(h) for h in headers) + ' |',
            '|' + '|'.join(sep[a] for a in aligns) + '|',
        ]
        self._md += ['| ' + ' | '.join(_md_escape(c) for c in r) + ' |'
                     for r in rows]
        self._md += ['']

        if self.echo:
            widths = [max(len(headers[i]), *(len(r[i]) for r in rows)) if rows
                      else len(headers[i]) for i in range(n)]
            if caption:
                print(f"  {caption}")
            print('  ' + '  '.join(
                headers[i].ljust(widths[i]) if aligns[i] == 'l'
                else headers[i].rjust(widths[i]) for i in range(n)))
            print('  ' + '  '.join('-' * widths[i] for i in range(n)))
            for r in rows:
                print('  ' + '  '.join(
                    r[i].ljust(widths[i]) if aligns[i] == 'l'
                    else r[i].rjust(widths[i]) for i in range(n)))
            print()
        return self

    def raw(self, text: str) -> 'Report':
        """Verbatim block -- for derivations and arithmetic, not tables."""
        self._md += ['```', text.rstrip(), '```', '']
        if self.echo:
            for line in text.rstrip().splitlines():
                print(f"  {line}")
            print()
        return self

    # ---- Output ------------------------------------------------------------

    @staticmethod
    def _plain(text: str) -> str:
        """Strip markdown emphasis for the terminal view."""
        return text.replace('**', '').replace('`', '')

    def save(self) -> str:
        with open(self.path, 'w') as f:
            f.write('\n'.join(self._md).rstrip() + '\n')
        return self.path
